### ISSUE TITLE
Use within iOS App

### ISSUE THREAD

**Issue by MarlowCharite** [timrogers/rapgenius#13]
Hey guys. I'm currently developing an iOS application that I need to pull lyrics for songs that I specify. I'm currently researching different apis that I can use to retrieve song lyrics. How can I use this within my iOS application? Thanks

**Comment by timrogers** [comment]
Apologies for missing this @MarlowCharite! You can't use this within an iOS application, but you can look at the code of the gem to see how the Genius API works. Alternatively, you can investigate yourself by following my guide at <http://timrogers.uk/2014/07/12/discovering-private-apis-with-charles-app/>.

**Comment by MarlowCharite** [comment]
@timrogers thank you for the follow up regardless. Appreciate it.
