### ISSUE TITLE
Lyric Annotations are scraped without a space

### ISSUE THREAD

**Issue by KevinMars** [timrogers/rapgenius#14]
When getting annotations we have to add a space between each one. In the line.rb file I added a space for explanations in end.join(" ")
Not sure if this is the optimal solution

**Comment by timrogers** [comment]
@KevinMars I've just pushed a new version, v1.0.5, which I believe should fix this. Can you confirm for me? Feel free to comment back if not - I could find many songs with multiple annotations to reproduce with.

**Comment by KevinMars** [comment]
Hey Tim, I'm not too good with ruby, but I'll check out the new version and
see if it runs smoothly
