### ISSUE TITLE
Support additional fields in the json

### ISSUE THREAD

**Issue by ianlin0126** [timrogers/rapgenius#17]
Awesome gem! 

Was wondering if you'd consider supporting additional fields in the json. Some of the fields I find valuable are:

- Whether an artist is primary or featured for a song (@type)
- Description dom (currently it just gets the children field)

Thanks!

**Comment by timrogers** [comment]
Sure! You'd be welcome to submit a pull request, or I can take a look at some point :+1:

**Comment by ianlin0126** [comment]
Actually I noticed you have the response field that includes the full json response from rapgenius api, so feel free to ignore my request :)
