### ISSUE TITLE
Terms of Service?

### ISSUE THREAD

**Issue by nategood** [timrogers/rapgenius#19]
The [Terms of Use](http://genius.com/static/terms) on Rap Genius (more generally genius.com) seem to explicitly prohibit this.

Specifically:

> Except as expressly authorized by Genius in writing, you agree not to modify, copy, frame, scrape, rent, lease, loan, sell, distribute or create derivative works based on the Service or the Genius Content, in whole or in part, except that the foregoing does not apply to your own User Content (as defined above) that you legally upload to the Service. In connection with your use of the Service you shall not engage in or use any data mining, robots, scraping or similar data gathering or extraction methods. Any use of the Service or the Genius Content other than as specifically authorized herein is strictly prohibited. 

I only bring it up because I'd like to pull lyric data from them as well and most of these sites tend to have a clause that includes that kind of language. Have you had any pushback?

**Comment by timrogers** [comment]
@nategood No pushback...only positive responses from the Genius tam :+1:

**Comment by nategood** [comment]
That's awesome to hear.

--
Nate Good

http://nategood.com
@nategood
